--- #YAML:1.0
name:                Sub-Become
version:             0.01
abstract:            Syntactic sugar to allow a sub to replace itself
license:             perl
author:              
    - Andy Armstrong <andy@hexten.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
